apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: torifirstapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: torifirstapp
    spec:
      containers:
      - name: torifirstapp
        image: amrocksandboxacr.azurecr.io/torifirstapp
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acraccess
---