apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: torifirstapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: torifirstapp
    spec:
      containers:
      - name: torifirstapp
        image: mkonkolowicz/torifirstapp:latest
        ports:
        - containerPort: 80